const text = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Donec ac odio tempor orci dapibus ultrices. Eu volutpat odio facilisis mauris. Magna fermentum iaculis eu non. Pellentesque sit amet porttitor eget dolor morbi non arcu risus. Tellus molestie nunc non blandit massa enim nec dui. Semper feugiat nibh sed pulvinar proin gravida. Tortor pretium viverra suspendisse potenti nullam ac. Quam adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna. Sit amet luctus venenatis lectus magna fringilla urna. Malesuada fames ac turpis egestas maecenas pharetra convallis. Nunc pulvinar sapien et ligula ullamcorper malesuada. Ac placerat vestibulum lectus mauris ultrices. Dui sapien eget mi proin sed libero. Et netus et malesuada fames ac turpis egestas. Purus sit amet volutpat consequat mauris nunc.\n' +
    '\n' +
    'Lectus magna fringilla urna porttitor rhoncus. Mi bibendum neque egestas congue quisque egestas diam in. Egestas fringilla phasellus faucibus scelerisque eleifend donec pretium vulputate sapien. Tortor consequat id porta nibh venenatis cras sed felis eget. Nisl nisi scelerisque eu ultrices vitae. Aliquam nulla facilisi cras fermentum odio eu feugiat. Amet facilisis magna etiam tempor orci eu. Pellentesque massa placerat duis ultricies lacus sed. Ultrices dui sapien eget mi. Et sollicitudin ac orci phasellus egestas.\n' +
    '\n' +
    'Amet nisl purus in mollis nunc sed. Pellentesque habitant morbi                             tristique senectus et netus et malesuada.                           Ipsum suspendisse ultrices gravida dictum fusce ut placerat orci. Adipiscing elit duis tristique sollicitudin nibh. Bibendum enim facilisis gravida neque convallis a cras semper auctor. Amet porttitor eget dolor morbi non arcu risus. Lorem ipsum dolor sit amet. Praesent elementum facilisis leo vel fringilla est ullamcorper eget nulla. Est ante in nibh mauris cursus mattis molestie a. Quam viverra orci sagittis eu volutpat. At imperdiet dui accumsan sit amet nulla facilisi morbi tempus. Dui accumsan sit amet nulla facilisi. Hendrerit gravida rutrum quisque non tellus orci ac auctor. Amet volutpat consequat mauris nunc congue nisi. Massa eget egestas purus viverra. Ultrices in iaculis nunc sed. Iaculis nunc sed augue lacus viverra vitae. Quam id leo in vitae.\n' +
    '\n' +
    'In nulla posuere sollicitudin aliquam                    ultrices. Facilisis gravida neque convallis a. Eu lobortis elementum                                  nibh tellus molestie nunc. In fermentum et sollicitudin ac orci. Id semper risus in hendrerit gravida rutrum quisque. Eget arcu dictum varius duis at. Mauris pharetra et ultrices neque. Morbi tempus iaculis urna id volutpat. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Varius sit amet mattis vulputate enim nulla aliquet porttitor lacus. Dignissim diam quis enim lobortis scelerisque fermentum.\n' +
    '\n' +
    'Adipiscing bibendum est ultricies integer + \n quis auctor elit sed. Enim lobortis scelerisque fermentum dui. Purus viverra accumsan in nisl nisi scelerisque eu ultrices. Enim nec dui nunc mattis enim ut tellus elementum sagittis. Nibh praesent tristique magna sit amet purus gravida quis. Tortor at risus viverra adipiscing at in. Morbi quis commodo odio aenean sed adipiscing diam donec adipiscing. Nibh tortor id aliquet lectus. Ut enim blandit volutpat maecenas volutpat. Fusce id velit ut tortor.' +
    '' +
    ' Nunc id cursus metus aliquam eleifend mi. Ac odio tempor orci dapibus ultrices in iaculis nunc sed. Gravida arcu ac tortor dignissim convallis aenean et tortor. Amet tellus cras adipiscing enim eu turpis egestas pretium. Viverra adipiscing at in tellus. Volutpat diam ut venenatis tellus in metus vulputate eu. Augue ut lectus arcu bibendum at varius vel pharetra vel.\n' +
    '\n' +
    'Urna neque viverra justo nec ultrices dui sapien eget mi. Iaculis urna id                  volutpat lacus laoreet non curabitur gravida arcu. Montes nascetur ridiculus mus mauris vitae. Viverra adipiscing at in tellus integer feugiat. Purus in mollis nunc sed id semper risus. Nibh tellus molestie nunc non blandit. Sem nulla pharetra diam sit. Tempor nec feugiat nisl pretium fusce id. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium. Vulputate ut pharetra sit amet aliquam id. Lorem donec massa sapien faucibus et molestie. Tempus imperdiet nulla malesuada pellentesque elit eget gravida cum sociis. Pellentesque habitant morbi tristique senectus et netus et. Iaculis at erat pellentesque adipiscing commodo elit at. Sem et tortor consequat id porta nibh venenatis cras sed. Aliquam id diam maecenas ultricies. Phasellus faucibus scelerisque eleifend donec pretium vulputate. Odio eu feugiat pretium nibh ipsum consequat. Odio morbi quis commodo odio.\n' +
    '\n' +
    'Ullamcorper morbi tincidunt ornare massa eget egestas purus viverra. Nunc congue                       nisi vitae suscipit tellus mauris. Enim lobortis scelerisque fermentum dui faucibus in ornare quam. Eget nulla facilisi etiam dignissim diam quis. Etiam dignissim diam quis enim lobortis. Et magnis dis parturient montes. Adipiscing tristique risus nec feugiat in fermentum posuere. Ultricies integer quis auctor elit. Mauris ultrices eros in cursus. Potenti nullam ac tortor vitae purus faucibus ornare suspendisse sed. Non curabitur gravida arcu ac. Amet justo donec enim diam vulputate ut pharetra. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus urna neque.\n' +
    '\n' +
    'Nec dui nunc mattis enim. Sit amet porttitor eget dolor morbi non arcu risus quis. In est ante in nibh mauris cursus mattis. Tortor aliquam nulla facilisi cras fermentum. Etiam tempor orci eu lobortis elementum nibh tellus molestie. Faucibus a pellentesque sit amet porttitor eget dolor. Lorem ipsum dolor sit amet. In fermentum posuere urna nec. Venenatis a condimentum vitae sapien. Arcu odio ut sem nulla pharetra diam sit. Phasellus faucibus scelerisque eleifend donec pretium. Neque ornare aenean euismod elementum nisi. Mauris rhoncus aenean vel elit scelerisque mauris. Sagittis eu volutpat odio facilisis mauris sit amet. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus quam.\n' +
    '\n' +
    'Urna condimentum mattis pellentesque id nibh tortor id. Sed risus ultricies tristique                                                                          nulla aliquet enim tortor. Magna ac placerat vestibulum lectus mauris ultrices eros. In eu mi bibendum neque egestas congue. Sed risus ultricies tristique nulla aliquet enim tortor. Sed blandit libero volutpat sed. Dui vivamus arcu felis bibendum ut tristique et egestas. Scelerisque eu ultrices vitae auctor eu augue ut. Eu consequat ac felis donec et odio pellentesque diam. Blandit cursus risus at ultrices. Nulla at volutpat diam ut venenatis tellus. Dolor morbi non arcu risus quis varius quam. Purus sit amet luctus venenatis lectus magna fringilla urna. Orci dapibus ultrices in iaculis nunc sed. In aliquam sem fringilla ut morbi tincidunt. Aliquet eget sit amet tellus cras adipiscing enim eu. Ut porttitor leo a diam sollicitudin tempor id. In fermentum posuere urna nec tincidunt praesent semper feugiat. Magna fermentum iaculis eu non diam phasellus vestibulum.\n' +
    '\n' +
    'Sit amet consectetur adipiscing elit ut aliquam purus. Egestas erat imperdiet sed euismod nisi porta lorem mollis aliquam. Gravida dictum fusce ut placerat orci. Morbi enim nunc faucibus a pellentesque sit amet porttitor eget. Fermentum iaculis eu non diam phasellus vestibulum. Mauris pharetra et ultrices neque. Sagittis eu volutpat odio facilisis mauris. At tellus at urna condimentum mattis pellentesque id nibh. Congue mauris rhoncus aenean vel elit scelerisque. Facilisi morbi tempus iaculis urna id volutpat. Malesuada proin libero nunc consequat interdum varius sit. Odio euismod lacinia at quis.';
export default text;